### ISSUE TITLE
RPC server crash if no argument is passed from client.

### ISSUE THREAD

**Issue by adrianObel** [tj/axon-rpc#15]
When you call a remote function, with no extra arguments passed, the rpc-server crashes with the error: TypeError: undefined is not a function
`client.call('add', 1, 2, function(err, n){
    console.log(n);
    // => 3
  })
`
Noticing how in the example two arguments are passed I don't see why not adding one at all should be a problem. Isn't  the callback in the argument always arguments.length - 1? 

Maybe there's something I failed to see, but couldn't really find out what it was.

Thanks in advance.

**Comment by bretcope** [comment]
You are correct, the callback is always arguments.length - 1, and no other arguments are required.

Can you give a complete example with both server and client code which reproduces this error?

**Comment by adrianObel** [comment]
Server

```
  var rpc = require('axon-rpc');
  var axon = require('axon');

  var rep = axon.socket('rep');
  var server = new rpc.Server(rep);

  rep.bind(3000);
  server.expose('check status', function(message, callback) {

    console.log(message);
    callback(null, 'Busy');
  });
```

Client

```
  var rpc = require('axon-rpc');
  var axon = require('axon');
  var req = axon.socket('req');
  var client = new rpc.Client(req);

  req.connect(3000);

  client.call('check status', function(err, res) {
    if(err) {
      console.log(err);
    }

    console.log(res);

  });
```

Error: 
  callback(null, 'Busy');
  ^
TypeError: undefined is not a function

**Comment by adrianObel** [comment]
Ah never mind :D silly mistake.
