### ISSUE TITLE
RPC Dispatcher

### ISSUE THREAD

**Issue by tracker1** [tj/axon-rpc#3]
It would be cool to take this one step further.. an RPC dispatcher... essentially your clients connect to a dispatcher, which has several workers connected to it.  The RPC request then gets forwarded to the next free worker, and the request/response routed appropriately.

**Comment by juliangruber** [comment]
and workers should take the item off the queue when they successfully processed them, otherwise they get queued in again.

**Comment by tj** [comment]
we have something like this in npm already but it's not really "released" yet, this could be built separately from axon-rpc though
