### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by gjohnson** [tj/axon-rpc#5]
@visionmedia figured I would get some feedback before I add this, something you would pull in? My main use-case is using `before` hooks to clean up some validation mess in my methods and then leverage `after` hooks for logging, redis-counters, etc.
### Option A:

_before hooks_

``` js
server.before(function(msg, next){
  // muck with msg if you want
  next();
});

server.before('add', function(msg, next){
  // muck with msg if you want
  next()
});
```

_after hooks_

``` js
server.after(function(res){
  console.log('generic logging')
});

server.after('add', function(res){
  console.log('sum = %s', res)
});
```
### Option B:

Reconfigure a few things to maintain a connect like function stack ala middleware.

``` js
server.use(before);
server.use(server.dispatch)
server.use(after);

function before(msg, next){

};

function after(msg, next){

}
```

**Comment by tj** [comment]
+1 for option A

**Comment by bretcope** [comment]
Pull request was closed nine months ago, so I'm closing this issue as well. If someone wants to suggest this sort of functionality in the future, they can start a new issue.
